package com.craftmaster2190.halloween.dragoncontrol;

import lombok.*;

@Getter
@RequiredArgsConstructor
public enum Pin {
  UPPER_LEFT_NECK_POSITIVE,
  UPPER_LEFT_NECK_NEGATIVE,
  UPPER_RIGHT_NECK_POSITIVE,
  UPPER_RIGHT_NECK_NEGATIVE,
  JAW_POSITIVE,
  JAW_NEGATIVE,
  EYES_POSITIVE,
  EYES_NEGATIVE,
  RIGHT_WING_POSITIVE,
  RIGHT_WING_NEGATIVE,
  LOWER_LEFT_NECK_POSITIVE,
  LOWER_LEFT_NECK_NEGATIVE,
  LOWER_RIGHT_NECK_POSITIVE,
  LOWER_RIGHT_NECK_NEGATIVE,
  MID_NECK_VERTICAL_POSITIVE,
  MID_NECK_VERTICAL_NEGATIVE,
  UPPER_LIP_POSITIVE,
  UPPER_LIP_NEGATIVE;

  private final int pinNumber = ordinal() + 1;
}
